seed_everything: true
trainer:
  enable_checkpointing: true
  accelerator: auto
  num_nodes: 1
  devices:
  - 0
  fast_dev_run: false
  max_epochs: 100
  precision: 32
  sync_batchnorm: false
  inference_mode: true
  accumulate_grad_batches: 2
  check_val_every_n_epoch: 1
model:
  dataset_type: raindrop_real
  train_datasets: D:\RaindropClarity-main\datasets\DayRainDrop_Train
  train_bs: 24
  test_datasets: D:\RaindropClarity-main\datasets\RainDrop_Valid
  test_bs: 7
  val_datasets: D:\RaindropClarity-main\datasets\DayRainDrop_Train
  val_bs: 6
  initlr: 0.0006
  weight_decay: 0.01
  crop_size: 128
  crop_size_test: 128
  num_workers: 2    
ckpt_path: raindrop_real
